[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@onchain-id/solidity/=lib/solidity/",
    "solidity/=lib/solidity/contracts/",
    "ERC-3643/=lib/ERC-3643/contracts/"
]

# optimize solidity config for localhost deployment
[profile.localhost]
optimizer = true
optimizer_runs = 200
via_ir = true  # optimize compiled size


[profile.baseSepolia]
optimizer = true
optimizer_runs = 200
via_ir = true  # optimize compiled size